# Define the services (containers) that make up your application.
services:
  # Define the PostgreSQL service.
  postgres:
    # Use the official PostgreSQL image from Docker Hub.
    # It's a good practice to pin to a specific version, e.g., 'postgres:16'.
    image: postgres:latest
    
    # Give the container a friendly name.
    container_name: dev_postgres_db_tracker
    
    # Always restart the container if it stops.
    # 'unless-stopped' is also a good option.
    restart: always
    
    # Set environment variables required for the PostgreSQL container.
    # ⚠️ For production, use Docker secrets or a .env file to handle sensitive data.
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: superdupersecretpassword1!
      POSTGRES_DB: dev_postgres_db_tracker
    
    # Map a port on the host machine to a port in the container.
    # Format: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "5432:5432"
      
    # Mount a volume to persist database data.
    # This links the 'postgres_data' volume (defined below)
    # to the directory where PostgreSQL stores its data inside the container.
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Define the volumes used by the services.
volumes:
  # Define the named volume for data persistence.
  postgres_data: