#!/usr/bin/env python3
"""
Script to help set up environment variables for the Corporate Spending Tracker.
"""

import os

def create_env_file():
    """Create a .env file with the current database configuration."""
    
    print("🔧 Setting up environment variables for Corporate Spending Tracker")
    print("=" * 70)
    
    # Database configuration
    print("\n📊 DATABASE CONFIGURATION")
    print("-" * 30)
    
    db_host = input("Enter database host (default: localhost): ").strip() or "localhost"
    db_port = input("Enter database port (default: 5432): ").strip() or "5432"
    db_name = input("Enter database name (default: corp_spend_tracker): ").strip() or "corp_spend_tracker"
    db_user = input("Enter database user (default: postgres): ").strip() or "postgres"
    db_password = input("Enter database password: ").strip()
    
    if not db_password:
        print("⚠️  Warning: No database password provided. Using 'postgres' as default.")
        db_password = "postgres"
    
    use_sqlite = input("Use SQLite instead of PostgreSQL? (y/N): ").strip().lower()
    use_sqlite = "true" if use_sqlite == 'y' else "false"
    
    # API Keys (optional)
    print("\n🔑 API KEYS (Optional)")
    print("-" * 30)
    print("These are optional for development. The app works with sample data.")
    print("Get API keys from:")
    print("  - FEC: https://api.open.fec.gov/developers/")
    print("  - ProPublica: https://www.propublica.org/datastore/api")
    print("  - SEC-API: https://sec-api.io/")
    
    fec_key = input("FEC API Key (optional): ").strip() or "your_fec_api_key_here"
    propublica_key = input("ProPublica API Key (optional): ").strip() or "your_propublica_api_key_here"
    sec_key = input("SEC-API.io Key (optional): ").strip() or "your_sec_api_key_here"
    
    # Create .env file content
    env_content = f"""# Corporate Spending Tracker Environment Configuration
# Generated by setup_env.py

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}
DB_HOST={db_host}
DB_PORT={db_port}

# Use SQLite for development (set to 'true' if PostgreSQL is not available)
USE_SQLITE={use_sqlite}

# =============================================================================
# DJANGO CONFIGURATION
# =============================================================================

SECRET_KEY=django-insecure-r55(7n1p8aad8d!)u_&6-4@!glt!ba!o93#%gajl(^8h^r9f#a
DEBUG=True

# =============================================================================
# API KEYS FOR DATA SOURCES
# =============================================================================
# These are OPTIONAL for development - the app works with sample data
# Add your API keys here to fetch real data from government sources

# Federal Election Commission (FEC) API
# Get your key from: https://api.open.fec.gov/developers/
FEC_API_KEY={fec_key}

# ProPublica Nonprofit API
# Get your key from: https://www.propublica.org/datastore/api
PROPUBLICA_API_KEY={propublica_key}

# SEC-API.io (for SEC EDGAR data)
# Get your key from: https://sec-api.io/
SEC_API_KEY={sec_key}
"""
    
    # Write to .env file
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✅ .env file created successfully!")
    print("\n📝 Next Steps:")
    print("1. If using PostgreSQL: python setup_postgres.py")
    print("2. Run migrations: python manage.py migrate")
    print("3. Create sample data: python manage.py create_sample_data")
    print("4. Test the setup: python manage.py test_ingestion")
    print("5. Start the servers:")
    print("   - Backend: python manage.py runserver")
    print("   - Frontend: cd ../frontend && python server.py")

if __name__ == "__main__":
    create_env_file()
