# Generated by Django 5.2.5 on 2025-08-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('cik', models.CharField(blank=True, max_length=20, null=True)),
                ('headquarters_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='PoliticalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_pac_id', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_party', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('election_cycle', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Political Contributions',
                'db_table': 'political_contributions',
            },
        ),
        migrations.CreateModel(
            name='CharitableGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_ein', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fiscal_year', models.IntegerField()),
                ('grant_description', models.TextField(blank=True, null=True)),
                ('recipient_category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charitable_grants', to='data_collection.company')),
            ],
            options={
                'verbose_name_plural': 'Charitable Grants',
                'db_table': 'charitable_grants',
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summaries', to='data_collection.company')),
            ],
            options={
                'verbose_name_plural': 'Financial Summaries',
                'db_table': 'financial_summaries',
                'unique_together': {('company', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='LobbyingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('specific_issues', models.TextField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbying_reports', to='data_collection.company')),
            ],
            options={
                'verbose_name_plural': 'Lobbying Reports',
                'db_table': 'lobbying_reports',
                'unique_together': {('company', 'year', 'quarter')},
            },
        ),
    ]
